/**
 * Registro único de métricas (R22-01). Fonte da verdade para dashboard, API, relatórios, regras, IA e app.
 * `docs/METRICS_DICTIONARY.md` é gerado a partir deste registro (scripts/gen-metrics-dictionary.ts).
 */

export type MetricUnit = "money" | "count" | "ratio" | "percent";

export type TimeBasis = "approval" | "financial_movement" | "acquisition_cohort";

export interface MetricDefinition {
  readonly id: MetricId;
  readonly label: string;
  readonly unit: MetricUnit;
  readonly formula: string;
  readonly denominator: string | null;
  readonly source: string;
  readonly refundPolicy: string;
  readonly notes?: string;
  /** Bases temporais em que a métrica é definida. */
  readonly bases: readonly TimeBasis[];
}

export const METRIC_IDS = [
  "orders_generated",
  "approved_orders_gross",
  "retained_orders",
  "gross_approved_revenue",
  "financial_reversals",
  "revenue_after_reversals",
  "org_revenue",
  "media_spend",
  "roas_gross",
  "roas_after_reversals",
  "mer",
  "cpa_approved",
  "cpa_retained",
  "avg_ticket_gross",
  "cpl",
  "link_ctr",
  "link_cpc",
  "cpm",
  "page_conversion",
  "payment_approval_rate",
  "fees",
  "contribution_after_media",
  "operating_result_estimated",
  "unattributed_orders",
  "breakeven_roas",
] as const;

export type MetricId = (typeof METRIC_IDS)[number];

const ALL: readonly TimeBasis[] = ["approval", "financial_movement", "acquisition_cohort"];
const APPROVAL_COHORT: readonly TimeBasis[] = ["approval", "acquisition_cohort"];

export const METRIC_DEFINITIONS: Record<MetricId, MetricDefinition> = {
  orders_generated: {
    id: "orders_generated",
    label: "Pedidos gerados",
    unit: "count",
    formula: "COUNT(DISTINCT pedido) com qualquer evento conhecido no período (criação na origem)",
    denominator: null,
    source: "orders (checkouts que enviam pedidos pendentes)",
    refundPolicy: "Não afetado por estornos",
    notes: "Indisponível quando o checkout só envia aprovações; nunca exibido como zero nesse caso.",
    bases: ["approval"],
  },
  approved_orders_gross: {
    id: "approved_orders_gross",
    label: "Pedidos aprovados brutos",
    unit: "count",
    formula: "COUNT(DISTINCT pedido) com primeira confirmação válida no período",
    denominator: null,
    source: "financial_entries tipo approval",
    refundPolicy: "Mantém pedidos depois estornados",
    bases: APPROVAL_COHORT,
  },
  retained_orders: {
    id: "retained_orders",
    label: "Pedidos retidos",
    unit: "count",
    formula: "Aprovados brutos que não foram integralmente revertidos até as_of",
    denominator: null,
    source: "financial_entries (approval, refund, chargeback, chargeback_reversal)",
    refundPolicy: "Estorno parcial permanece retido e identificado",
    bases: APPROVAL_COHORT,
  },
  gross_approved_revenue: {
    id: "gross_approved_revenue",
    label: "Receita bruta aprovada",
    unit: "money",
    formula: "Σ valor confirmado das transações (uma vez por transação; sem itens, parcelas ou repasses)",
    denominator: null,
    source: "financial_entries tipo approval",
    refundPolicy: "Bruto original preservado",
    bases: ALL,
  },
  financial_reversals: {
    id: "financial_reversals",
    label: "Estornos financeiros",
    unit: "money",
    formula: "Σ reembolsos efetivos + chargebacks efetivos − disputas ganhas (sem dupla dedução)",
    denominator: null,
    source: "financial_entries tipos refund, chargeback, chargeback_reversal",
    refundPolicy: "Por aprovação: estornos da coorte até as_of; por movimento: na data do estorno",
    bases: ALL,
  },
  revenue_after_reversals: {
    id: "revenue_after_reversals",
    label: "Receita após estornos",
    unit: "money",
    formula: "Receita bruta aprovada − estornos financeiros (mesma base)",
    denominator: null,
    source: "financial_entries",
    refundPolicy: "Deduz estornos da mesma base de análise",
    bases: ALL,
  },
  org_revenue: {
    id: "org_revenue",
    label: "Receita da organização",
    unit: "money",
    formula:
      "Participação informada pela origem (após reversões) + receita após estornos de pedidos em que a organização é produtora sem participação informada",
    denominator: null,
    source: "financial_entries tipos org_share/org_share_reversal; papel da conexão",
    refundPolicy: "Redução proporcional da participação é rotulada como estimada",
    notes: "Afiliado/coprodutor sem participação informada fica indisponível (parcial), nunca igual ao bruto.",
    bases: ALL,
  },
  media_spend: {
    id: "media_spend",
    label: "Investimento em mídia",
    unit: "money",
    formula: "Σ gasto importado (snapshot mais recente por entidade/dia) + gastos manuais validados",
    denominator: null,
    source: "ad_spend_daily (origem: API da rede, CSV ou manual)",
    refundPolicy: "Não se aplica",
    notes: "Sem sincronização ou cobertura parcial → indisponível/parcial, não zero.",
    bases: ALL,
  },
  roas_gross: {
    id: "roas_gross",
    label: "ROAS bruto",
    unit: "ratio",
    formula: "Receita bruta atribuída / investimento da mesma entidade e período",
    denominator: "Investimento em mídia",
    source: "order_attributions + ad_spend_daily",
    refundPolicy: "Não deduz estornos",
    bases: APPROVAL_COHORT,
  },
  roas_after_reversals: {
    id: "roas_after_reversals",
    label: "ROAS após estornos",
    unit: "ratio",
    formula: "Receita atribuída após estornos / investimento correspondente",
    denominator: "Investimento em mídia",
    source: "order_attributions + financial_entries + ad_spend_daily",
    refundPolicy: "Deduz estornos da coorte até as_of",
    bases: APPROVAL_COHORT,
  },
  mer: {
    id: "mer",
    label: "MER",
    unit: "ratio",
    formula: "Receita total da operação / gasto total de mídia (não é ROAS atribuído)",
    denominator: "Gasto total de mídia",
    source: "financial_entries + ad_spend_daily",
    refundPolicy: "Usa receita após estornos da base escolhida",
    bases: ALL,
  },
  cpa_approved: {
    id: "cpa_approved",
    label: "CPA aprovado",
    unit: "money",
    formula: "Investimento / pedidos aprovados creditados pela regra selecionada",
    denominator: "Pedidos aprovados creditados",
    source: "ad_spend_daily + order_attributions",
    refundPolicy: "Não considera estornos",
    bases: APPROVAL_COHORT,
  },
  cpa_retained: {
    id: "cpa_retained",
    label: "CPA retido",
    unit: "money",
    formula: "Investimento / pedidos retidos creditados pela regra selecionada",
    denominator: "Pedidos retidos creditados",
    source: "ad_spend_daily + order_attributions + financial_entries",
    refundPolicy: "Exclui pedidos integralmente revertidos",
    bases: APPROVAL_COHORT,
  },
  avg_ticket_gross: {
    id: "avg_ticket_gross",
    label: "Ticket médio bruto",
    unit: "money",
    formula: "Receita bruta aprovada / pedidos aprovados brutos",
    denominator: "Pedidos aprovados brutos",
    source: "financial_entries",
    refundPolicy: "Bruto",
    bases: APPROVAL_COHORT,
  },
  cpl: {
    id: "cpl",
    label: "CPL",
    unit: "money",
    formula: "Investimento / leads definidos e deduplicados da mesma fonte/coorte",
    denominator: "Leads deduplicados",
    source: "tracking_events Lead + ad_spend_daily",
    refundPolicy: "Não se aplica",
    bases: ["approval"],
  },
  link_ctr: {
    id: "link_ctr",
    label: "CTR de link",
    unit: "percent",
    formula: "Cliques no link / impressões",
    denominator: "Impressões",
    source: "ad_insights (métricas reportadas pela rede)",
    refundPolicy: "Não se aplica",
    bases: ["approval"],
  },
  link_cpc: {
    id: "link_cpc",
    label: "CPC de link",
    unit: "money",
    formula: "Investimento / cliques no link",
    denominator: "Cliques no link",
    source: "ad_insights",
    refundPolicy: "Não se aplica",
    bases: ["approval"],
  },
  cpm: {
    id: "cpm",
    label: "CPM",
    unit: "money",
    formula: "Investimento / impressões × 1.000",
    denominator: "Impressões",
    source: "ad_insights",
    refundPolicy: "Não se aplica",
    bases: ["approval"],
  },
  page_conversion: {
    id: "page_conversion",
    label: "Conversão da página",
    unit: "percent",
    formula: "Pedidos atribuídos / sessões elegíveis observadas",
    denominator: "Sessões elegíveis observadas pelo SDK",
    source: "sessions + order_attributions",
    refundPolicy: "Bruto",
    notes: "Sessões sem consentimento ou bloqueadas não são observáveis; limitação explícita.",
    bases: ["approval"],
  },
  payment_approval_rate: {
    id: "payment_approval_rate",
    label: "Aprovação de pagamento",
    unit: "percent",
    formula: "Pedidos aprovados / pedidos elegíveis com tentativa de pagamento",
    denominator: "Pedidos com tentativa de pagamento conhecida",
    source: "payment_transactions",
    refundPolicy: "Não se aplica",
    notes: "Indisponível quando o conector não envia tentativas pendentes/recusadas.",
    bases: ["approval"],
  },
  fees: {
    id: "fees",
    label: "Taxas efetivas",
    unit: "money",
    formula: "Σ taxas informadas pela origem + taxas estimadas por tabela vigente (rotuladas)",
    denominator: null,
    source: "financial_entries tipo fee; fee_schedules",
    refundPolicy: "Taxa não devolvida em estorno salvo informação da origem",
    bases: ALL,
  },
  contribution_after_media: {
    id: "contribution_after_media",
    label: "Contribuição após mídia",
    unit: "money",
    formula: "Receita da organização após estornos − custos variáveis conhecidos (taxas etc.) − investimento",
    denominator: null,
    source: "financial_entries + custos + ad_spend_daily",
    refundPolicy: "Após estornos",
    notes: "Custos materiais ausentes → resultado parcial com a lista de custos faltantes. Não é lucro líquido.",
    bases: ALL,
  },
  operating_result_estimated: {
    id: "operating_result_estimated",
    label: "Resultado operacional estimado",
    unit: "money",
    formula: "Contribuição após mídia − despesas operacionais incluídas (critério de rateio informado)",
    denominator: null,
    source: "contribuição + operating_expenses",
    refundPolicy: "Após estornos",
    bases: ALL,
  },
  unattributed_orders: {
    id: "unattributed_orders",
    label: "Vendas sem atribuição",
    unit: "count",
    formula: "Pedidos aprovados sem atribuição elegível pela política ativa (com motivo)",
    denominator: null,
    source: "order_attributions",
    refundPolicy: "Bruto",
    bases: APPROVAL_COHORT,
  },
  breakeven_roas: {
    id: "breakeven_roas",
    label: "ROAS de equilíbrio",
    unit: "ratio",
    formula: "1 / margem de contribuição antes da mídia",
    denominator: "Margem de contribuição antes da mídia (deve ser positiva)",
    source: "receita da organização após estornos − custos variáveis conhecidos",
    refundPolicy: "Após estornos",
    notes: "Não calculado com margem não positiva, moedas misturadas ou custos materiais ausentes.",
    bases: ALL,
  },
};
